default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: db
  username: root
  password: password
  database: new_app_development

development:
  <<: *default
  database: new_app_development  
  username: root
  password: password
  host: db
  port: 3306

test:
  <<: *default
  database: new_app_test
  username: root
  password: password
  host: db
  port: 3306

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %> 
  pool: 10

  primary: &primary_production
    <<: *default
    database: app_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
