default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  database: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).path.sub("/", "") : "app_production" %>
  username: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).user : ENV['DB_USERNAME'] %>
  password: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).password : ENV['DB_PASSWORD'] %>
  host: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).host : ENV['DB_HOST'] %>
  port: <%= ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']).port : 3306 %>
  timeout: 5000

development:
  <<: *default
  database: new_app_development  # `app_development` ではなく `new_app_development` に統一

test:
  <<: *default
  database: new_app_test

production:
  primary: &primary_production
    <<: *default
    database: app_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
