default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: localhost
  username: root
  password: password
  database: new_app_development

development:
  <<: *default
  database: new_app_development  
  username: root
  password: password
  host: localhost
  port: 3306

test:
  <<: *default
  database: new_app_test

  username: root
  password: password
  host: localhost
  port: 3306

production: &primary
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  url: <%= ENV['DATABASE_URL'] %> 

cache:
  <<: *primary
  database: app_production_cache
  migrations_paths: db/cache_migrate
queue:
  <<: *primary
  database: app_production_queue
  migrations_paths: db/queue_migrate
cable:
  <<: *primary
  database: app_production_cable 
  migrations_paths: db/cable_migrate